screener/urls.py
from django.urls import path

from . import views

app_name = "screener"

urlpatterns = [
    path("", views.index, name="index"),
    path("search/<str:search_term>", views.search),
    path("stock_info/<str:symbol>", views.stock_info, name="stock_info"),
    path("stock_info/add_stock/<str:stock_id>",
         views.add_stock, name="add_stock"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("my_stocks/", views.my_stocks, name="my_stocks")
]

stock_screener/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("screener.urls"))
]

screener/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Stock(models.Model):
    symbol = models.CharField(max_length=10)
    security_name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.symbol} | {self.security_name}"


class User(AbstractUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f"{self.username}"


class UserStock(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.user} - {self.stock}"

screener/forms.py
from django import forms


class RegisterForm(forms.Form):
    first_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={"placeholder": "First Name"}))
    last_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={"placeholder": "Last Name"}))
    email = forms.EmailField(label="", widget=forms.TextInput(
        attrs={"placeholder": "Email"}))
    username = forms.CharField(label="", widget=forms.TextInput(
        attrs={"placeholder": "Username"}))
    password = forms.CharField(label="", widget=forms.PasswordInput(
        attrs={"placeholder": "Password"}))


class LoginForm(forms.Form):
    username = forms.CharField(label="", widget=forms.TextInput(
        attrs={"placeholder": "Username"}))
    password = forms.CharField(label="", widget=forms.PasswordInput(
        attrs={"placeholder": "Password"}))

screener/views.py
import requests
from bs4 import BeautifulSoup
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, JsonResponse
from django.shortcuts import redirect, render

from screener.forms import LoginForm, RegisterForm

from .models import Stock, UserStock
from .utils import logout_required, remove_duplicates


def index(request: HttpRequest):
    return render(request, "screener/index.html")


def stock_info(request: HttpRequest, symbol: str):
    stock_url = f"https://finance.yahoo.com/quote/{symbol}"
    page = requests.get(stock_url)

    if page.status_code == 404:
        return render(request, "screener/404.html")

    soup = BeautifulSoup(page.content, "html.parser")

    stock_id = Stock.objects.get(symbol=symbol).id
    stock_name = soup.find(name="h1", class_="D(ib) Fz(18px)").text
    stock_price = soup.find(name="fin-streamer", class_="Fw(b) Fz(36px) Mb(-4px) D(ib)",
                            attrs={"data-field": "regularMarketPrice"}).text
    stock_change_value = soup.find(name="fin-streamer", class_="Fw(500) Pstart(8px) Fz(24px)",
                                   attrs={"data-field": "regularMarketChange"}).findChild("span").text
    stock_change_percent = soup.find(name="fin-streamer", class_="Fw(500) Pstart(8px) Fz(24px)", attrs={
        "data-field": "regularMarketChangePercent"}).findChild("span").text
    previous_close = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "PREV_CLOSE-value"}).text
    open = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "OPEN-value"}).text
    bid = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "BID-value"}).text
    ask = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "ASK-value"}).text
    days_range = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "DAYS_RANGE-value"}).text
    fifty_two_week_range = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "FIFTY_TWO_WK_RANGE-value"}).text
    volume = soup.find(name="fin-streamer",
                       attrs={"data-field": "regularMarketVolume"})["value"]
    average_volume = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "AVERAGE_VOLUME_3MONTH-value"}).text
    market_cap = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "MARKET_CAP-value"}).text
    beta = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "BETA_5Y-value"}).text
    pe_ratio = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "PE_RATIO-value"}).text
    eps = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "EPS_RATIO-value"}).text
    earnings_date = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "EARNINGS_DATE-value"}).text
    one_year_target = soup.find(name="td", class_="Ta(end) Fw(600) Lh(14px)", attrs={
        "data-test": "ONE_YEAR_TARGET_PRICE-value"}).text

    context = {
        "stock_id": stock_id,
        "stock_name": stock_name,
        "stock_price": stock_price,
        "stock_change_value": stock_change_value,
        "stock_change_percent": stock_change_percent,
        "previous_close": previous_close,
        "open": open,
        "bid": bid,
        "ask": ask,
        "days_range": days_range,
        "fifty_two_week_range": fifty_two_week_range,
        "volume": volume,
        "average_volume": average_volume,
        "market_cap": market_cap,
        "beta": beta,
        "pe_ratio": pe_ratio,
        "eps": eps,
        "earnings_date": earnings_date,
        "one_year_target": one_year_target
    }

    # context = {
    #     "stock_id": "1",
    #     "stock_name": "AAPL",
    #     "stock_price": "173.00",
    #     "stock_change_value": "+0.12",
    #     "stock_change_percent": "(+0.07%)",
    #     "previous_close": "172.88",
    #     "open": "170.91",
    #     "bid": "172.93 x 1100",
    #     "ask": "173.01 x 1000",
    #     "days_range": "169.94 - 174.01",
    #     "fifty_two_week_range": "124.17 - 198.23",
    #     "volume": "55,856,506",
    #     "average_volume": "58,053,110",
    #     "market_cap": "2.705T",
    #     "beta": "1.31",
    #     "pe_ratio": "29.03",
    #     "eps": "5.96",
    #     "earnings_date": "Nov 02, 2023",
    #     "forward_dividend_and_yield": "0.96 (0.56%)",
    #     "ex_dividend_date": "Aug 11, 2023",
    #     "target_mean": "187.73"
    # }

    if request.user.is_authenticated:
        user_id = request.user.id

        if UserStock.objects.filter(user=user_id).filter(stock=stock_id):
            context["stock_exists"] = True

    return render(request, "screener/stock_info.html", context)


@login_required
def add_stock(request: HttpRequest, stock_id):
    user = request.user
    stock = Stock.objects.get(pk=stock_id)

    if "add" in request.POST:
        new_stock = UserStock(user=user, stock=stock)
        new_stock.save()
    elif "remove" in request.POST:
        UserStock.objects.get(user=user, stock=stock).delete()

    return redirect("screener:my_stocks")


def search(request: HttpRequest, search_term: str):
    # Get the first 5 values where the stock symbol matches the search term
    symbols = Stock.objects.filter(symbol__contains=search_term).values()[:5]
    formatted_results = [
        f"{entry['symbol']} | {entry['security_name']}" for entry in symbols]

    # If there were less than 5 results from the query above, get the next 5 values where the security's name matches the search term
    if len(symbols) < 5:
        security_names = Stock.objects.filter(
            security_name__contains=search_term).values()[:5]
        formatted_results = formatted_results + \
            [f"{entry['symbol']} | {entry['security_name']}" for entry in security_names]
        # to remove duplicates while maintaing the order
        formatted_results = remove_duplicates(formatted_results)

    return JsonResponse({"data": formatted_results})


@logout_required
def register(request: HttpRequest):
    form = RegisterForm()

    if request.method == "POST":
        User = get_user_model()
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]

            User.objects.create_user(username=username, email=email,
                                     password=password, first_name=first_name, last_name=last_name)

            messages.add_message(request, messages.SUCCESS,
                                 "Account created successfully!")

            return redirect("screener:login")
        else:
            print(form.errors)

    return render(request, "screener/register.html", {"form": form})


@logout_required
def login(request: HttpRequest):
    form = LoginForm()

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth_login(request, user)

                return redirect("screener:index")
            else:
                messages.add_message(request, messages.ERROR,
                                     "Invalid username/password")
                print("Invalid username/password", user)
        else:
            print(form.errors)

    return render(request, "screener/login.html", {"form": form})


@login_required
def logout(request: HttpRequest):
    if request.user.is_authenticated:
        auth_logout(request)

    return redirect("screener:index")


@login_required(login_url="/login")
def my_stocks(request: HttpRequest):
    user_id = request.user.id
    user_stocks = UserStock.objects.filter(user=user_id)

    stocks = []

    for stock in user_stocks:
        stocks.append(stock.stock)

    return render(request, "screener/my_stocks.html", {"user_stocks": stocks})

screener/templates/screener/base.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chalky's Stock Screener</title>
    
    <link rel="stylesheet" href="{% static 'screener/css/global.css' %}" />
    <link rel="icon" href="{% static 'screener/favicon.png' %}" type="image/x-icon">
    {% block styling %}{% endblock styling %}
  </head>
  <body>
    <nav>
        <a href="{% url 'screener:index' %}"><h1>Chalky's Stock Screener</h1></a>
        <div>
          {% if user.is_authenticated %}
            <a href="{% url 'screener:my_stocks' %}">My Stocks</a>
            <a href="{% url 'screener:logout' %}">Logout</a>
          {% else %}
            <a href="{% url 'screener:login' %}">Login</a>
            <a href="{% url 'screener:register' %}">Register</a>
          {% endif %}
        </div>
    </nav>
    {% block content %}{% endblock content %}
  </body>
</html>

screener/templates/screener/index.html
{% extends "screener/base.html" %}
{% load static %}

{% block styling %}
  <link rel="stylesheet" href="{% static 'screener/css/index.css' %}">
{% endblock styling %}

{% block content %}
  <form>
    <div class="serach-box-container">
      <input type="text" placeholder="Search ticker" onkeyup="search(event)">
      <ul class="search-results-list"></ul>
    </div>
    <button type="submit">Go</button>
  </form>

  <script src="{% static "screener/js/search.js" %}"></script>
{% endblock content %}

screener/templates/screener/login.html
{% extends "screener/base.html" %}
{% load static %}

{% block styling %}
  <link rel="stylesheet" href="{% static 'screener/css/login.css' %}">
{% endblock styling %}

{% block content %}
  <div class="wrapper">
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
    {% endif %}
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit">Login</button>
    </form>
  </div>
{% endblock content %}

screener/templates/screener/my_stocks.html
{% extends "screener/base.html" %}
{% load static %}

{% block styling %}
  <link rel="stylesheet" href="{% static 'screener/css/my_stocks.css' %}">
{% endblock styling %}

{% block content %}
  <ul>
    {% for stock in user_stocks %}
      <li><a href="{% url 'screener:stock_info' stock.symbol %}">{{ stock }}</a></li>
    {% endfor %}
  </ul>
{% endblock content %}

screener/templates/screener/register.html
{% extends "screener/base.html" %}
{% load static %}

{% block styling %}
  <link rel="stylesheet" href="{% static 'screener/css/register.css' %}">
{% endblock styling %}

{% block content %}
  <div class="wrapper">
    <form method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit">Register</button>
    </form>
  </div>
{% endblock content %}

screener/templates/screener/stock_info.html
{% extends "screener/base.html" %}
{% load static %}

{% block styling %}
  <link rel="stylesheet" href="{% static 'screener/css/stock_info.css' %}">
{% endblock styling %}

{% block content %}
  <div class="container">
    <div class="heading-container">
      <h2>{{ stock_name }}</h2>
      <div class="finances-container">
        <em data-field="stock_price">{{ stock_price }}</em>
        <em data-field="stock_change_value">{{ stock_change_value }}</em>
        <em data-field="stock_change_percent">{{ stock_change_percent }}</em>
      </div>
    </div>
    <div class="horizontal-line"></div>
    <div class="summary-container">
      <div class="summary-box-container">
        <span>Previous Close</span><span>{{ previous_close }}</span>
      </div>
      <div class="summary-box-container">
        <span>Market Cap</span><span>{{ market_cap }}</span>
      </div>
      <div class="summary-box-container">
        <span>Open</span><span>{{ open }}</span>
      </div>
      <div class="summary-box-container">
        <span>Beta (5Y Monthly)</span><span>{{ beta }}</span>
      </div>
      <div class="summary-box-container">
        <span>Bid</span><span>{{ bid }}</span>
      </div>
      <div class="summary-box-container">
        <span>PE Ratio (TTM)</span><span>{{ pe_ratio }}</span>
      </div>
      <div class="summary-box-container">
        <span>Ask</span><span>{{ ask }}</span>
      </div>
      <div class="summary-box-container">
        <span>EPS (TTM)</span><span>{{ eps }}</span>
      </div>
      <div class="summary-box-container">
        <span>Day's Range</span><span>{{ days_range }}</span>
      </div>
      <div class="summary-box-container">
        <span>Earnings Date</span><span>{{ earnings_date }}</span>
      </div>
      <div class="summary-box-container">
        <span>52 Week Range</span><span>{{ fifty_two_week_range }}</span>
      </div>
      <div class="summary-box-container">
        <span>Volume</span><span>{{ volume }}</span>
      </div>
      <div class="summary-box-container">
        <span>Avg. Volume</span><span>{{ average_volume }}</span>
      </div>
    </div>
    <form method="POST" action="{% url 'screener:add_stock' stock_id %}">
      {% csrf_token %}
      {% if stock_exists and user.is_authenticated  %}
        <button type="submit" name="remove">Remove</button>
      {% elif user.is_authenticated %}
        <button type="submit" name="add">Add</button>
      {% endif %}
    </form>
  </div>

  <script src="{% static "screener/js/stock_info.js" %}"></script>
{% endblock content %}